### ISSUE TITLE
Using and contributing / synergies to HPI Schul-Cloud

### ISSUE THREAD

**Issue by janrenz** [Viktoriaschule/App#205]
Hi,

just wanted to let you know that know after HPI Schul-Cloud is open for all schools, you might want to look at our code (we also have a flutter app) and check if there are synergies here.

Jan

**Comment by provokateurin** [comment]
We are not sure if it is possible to use any of the code, because we use the specific infrastructure of our school and everything is tailored to that.
Also our school decided against HPI Schul-Cloud for various reasons and therefore won't use your infrastructure.
